/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfissionalAgendaRouteImport } from './routes/profissional.agenda'
import { Route as ClienteDashboardRouteImport } from './routes/cliente.dashboard'
import { Route as AdminPlanosRouteImport } from './routes/admin.planos'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAssinantesRouteImport } from './routes/admin.assinantes'
import { Route as AdminAgendaRouteImport } from './routes/admin.agenda'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionalAgendaRoute = ProfissionalAgendaRouteImport.update({
  id: '/profissional/agenda',
  path: '/profissional/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteDashboardRoute = ClienteDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ClienteRoute,
} as any)
const AdminPlanosRoute = AdminPlanosRouteImport.update({
  id: '/admin/planos',
  path: '/admin/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssinantesRoute = AdminAssinantesRouteImport.update({
  id: '/admin/assinantes',
  path: '/admin/assinantes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/admin/agenda',
  path: '/admin/agenda',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/assinantes': typeof AdminAssinantesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/cliente/dashboard': typeof ClienteDashboardRoute
  '/profissional/agenda': typeof ProfissionalAgendaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/assinantes': typeof AdminAssinantesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/cliente/dashboard': typeof ClienteDashboardRoute
  '/profissional/agenda': typeof ProfissionalAgendaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/assinantes': typeof AdminAssinantesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/cliente/dashboard': typeof ClienteDashboardRoute
  '/profissional/agenda': typeof ProfissionalAgendaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cliente'
    | '/login'
    | '/signup'
    | '/admin/agenda'
    | '/admin/assinantes'
    | '/admin/dashboard'
    | '/admin/planos'
    | '/cliente/dashboard'
    | '/profissional/agenda'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cliente'
    | '/login'
    | '/signup'
    | '/admin/agenda'
    | '/admin/assinantes'
    | '/admin/dashboard'
    | '/admin/planos'
    | '/cliente/dashboard'
    | '/profissional/agenda'
  id:
    | '__root__'
    | '/'
    | '/cliente'
    | '/login'
    | '/signup'
    | '/admin/agenda'
    | '/admin/assinantes'
    | '/admin/dashboard'
    | '/admin/planos'
    | '/cliente/dashboard'
    | '/profissional/agenda'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClienteRoute: typeof ClienteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminAssinantesRoute: typeof AdminAssinantesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminPlanosRoute: typeof AdminPlanosRoute
  ProfissionalAgendaRoute: typeof ProfissionalAgendaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissional/agenda': {
      id: '/profissional/agenda'
      path: '/profissional/agenda'
      fullPath: '/profissional/agenda'
      preLoaderRoute: typeof ProfissionalAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/dashboard': {
      id: '/cliente/dashboard'
      path: '/dashboard'
      fullPath: '/cliente/dashboard'
      preLoaderRoute: typeof ClienteDashboardRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/admin/planos': {
      id: '/admin/planos'
      path: '/admin/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminPlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/assinantes': {
      id: '/admin/assinantes'
      path: '/admin/assinantes'
      fullPath: '/admin/assinantes'
      preLoaderRoute: typeof AdminAssinantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/admin/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClienteRouteChildren {
  ClienteDashboardRoute: typeof ClienteDashboardRoute
}

const ClienteRouteChildren: ClienteRouteChildren = {
  ClienteDashboardRoute: ClienteDashboardRoute,
}

const ClienteRouteWithChildren =
  ClienteRoute._addFileChildren(ClienteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClienteRoute: ClienteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AdminAgendaRoute: AdminAgendaRoute,
  AdminAssinantesRoute: AdminAssinantesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminPlanosRoute: AdminPlanosRoute,
  ProfissionalAgendaRoute: ProfissionalAgendaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
